# Generated by Django 5.0.7 on 2025-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountspayable",
            name="vendor",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="accountsreceivable",
            name="client",
            field=models.CharField(max_length=255),
        ),
    ]
