# Generated by Django 5.0.7 on 2025-08-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_accountspayable_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="source",
            field=models.CharField(max_length=255),
        ),
    ]
